# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2015

# Custom your favicon.ico in `site/source`
favicon: /favicon.png

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  Archives: /archives/
  Tags: /tags
  # Categories: /categories
  About: /about

# ===========================================
# Theme Settings
# ===========================================
# color: default | mint green | cobalt blue | hot pink | dark violet
color: default

# default page mode: default | archives
mode: default

toc: true

# jQuery fancybox
fancybox: true

pjax: true

copyright:
  enable: true
  # https://creativecommons.org/
  license: '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>'

reward:
  enable: true
  qrCode:
    wechat: /image/reward/wechat.png
    alipay: /image/reward/alipay.png

# ===========================================
# Social links Settings
# ===========================================
social:
  email: kchen2991@gmail.com
  stack-overflow:
  twitter:
  facebook: https://www.facebook.com/quentin.chenkun
  linkedin:
  google:
  github: https://github.com/kchen0x
  weibo:
  zhihu: https://www.zhihu.com/people/chen-kun-92-07/activities
  douban:
  pocket:
  tumblr:
  instagram:

# ===========================================
# Third Party Services Settings
# ===========================================

# LeanCloud
leancloud:
  app_id: E6WKI3ciNvoyQWfb6qdM50rJ-gzGzoHsz
  app_key: wVKlG50ntVertqEOw4aQEVwI

# Baidu Analytics
baidu_analytics:
# Baidu Verification
baidu_verification:

# Google Analytics
google_analytics: UA-41464607-2
# Google Verification
google_verification:

# Disqus
disqus_shortname: kchen

#Changyan
changyan:
  appid:
  appkey:

#LiveRe
livere_datauid:

# ===========================================
# Version
# ===========================================
version: 2.10.1
